import Head from "next/head";
import SideNavbar from "../components/SideNavbar";
import Activitys from "../components/Activitys";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SMA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavbar/>
      <Activitys/>
      </div>
  );
}
